// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmMQi5rc4zkq43JOVzdOkH7MqRyogQZk',
    appId: '1:782290592124:web:7cc0471a4bb88c3e2bc4f9',
    messagingSenderId: '782290592124',
    projectId: 'student-commute',
    authDomain: 'student-commute.firebaseapp.com',
    storageBucket: 'student-commute.appspot.com',
    measurementId: 'G-EC695YMRZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3caO-9V01alsMYbgZ-wGyul_CuHi2KA',
    appId: '1:782290592124:android:e882b625e494eb2c2bc4f9',
    messagingSenderId: '782290592124',
    projectId: 'student-commute',
    storageBucket: 'student-commute.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGTVm8lS_bS5ukgC4t1pT6JCmeOEU8Hw',
    appId: '1:782290592124:ios:c2aa5a87dfa2f4342bc4f9',
    messagingSenderId: '782290592124',
    projectId: 'student-commute',
    storageBucket: 'student-commute.appspot.com',
    iosBundleId: 'com.example.studentCommute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGTVm8lS_bS5ukgC4t1pT6JCmeOEU8Hw',
    appId: '1:782290592124:ios:63b16bf070367bed2bc4f9',
    messagingSenderId: '782290592124',
    projectId: 'student-commute',
    storageBucket: 'student-commute.appspot.com',
    iosBundleId: 'com.example.studentCommute.RunnerTests',
  );
}
